# define base docker image
FROM openjdk:21
# VOLUME
LABEL maintainer="javaguides.net"
ADD target/user-management-0.0.1-SNAPSHOT.jar user-management-docker.jar
ENTRYPOINT ["java","-jar","user-management-docker.jar"]